In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("cleaned-data.csv", index_col=0)
df

,Team,Student Number,Student Name,Car Name,Model Year,MPG,Weight (lbs),Weight Distribution (%),Length (in),Width (in),Height (in),Cylinders,Engine Displacement (L),Transmission Type,Transmission Speeds
1,1,1,Jack McCartney,Mazda Miata MX-5,1992.0,23.0,2121.00,53.0,155.51,66.14,48.03,4.0,1.6,0.0,5.0
2,1,1,Jack McCartney,Chyrsler New Yorker,1992.0,19.0,3337.00,63.0,193.70,68.90,53.54,6.0,3.3,1.0,4.0
3,1,1,Jack McCartney,Ford Crown Victoria,1992.0,20.0,3738.00,56.0,212.60,77.95,56.69,8.0,4.6,1.0,4.0
4,1,1,Jack McCartney,Cadillac Seville,1992.0,18.0,3557.00,63.0,204.33,74.41,53.94,8.0,4.9,1.0,4.0
5,1,1,Jack McCartney,Lexus LS400,1990.0,18.0,3760.00,54.0,196.85,71.65,55.12,8.0,4.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,25,5,Alex Bloom,Ford Mustang,2010.0,19.0,3750.00,53.0,188.19,74.02,55.91,8.0,4.6,1.0,5.0
622,25,5,Alex Bloom,Audi Q5 5DR SUV 2.0,2012.0,22.0,4089.57,53.0,182.28,74.80,65.35,4.0,2.0,1.0,8.0
623,25,5,Alex Bloom,Maserati Quattroporte,2012.0,15.0,4376.50,47.0,198.20,74.41,56.69,8.0,4.7,1.0,6.0
624,25,5,Alex Bloom,Mercedez-Benz CLS 550,2009.0,23.0,3982.00,52.0,193.70,73.62,54.72,8.0,5.5,1.0,6.0
625,25,5,Alex Bloom,Toyota FJ Cruiser,2009.0,26.0,4286.00,53.0,177.17,75.20,72.05,4.0,2.0,1.0,5.0

# Impute Missing Values with Mean

In [3]:
cols_with_na = df.columns[df.isnull().any()]
imputer = SimpleImputer(strategy="mean")
df[cols_with_na] = imputer.fit_transform(df[cols_with_na])
df

,Team,Student Number,Student Name,Car Name,Model Year,MPG,Weight (lbs),Weight Distribution (%),Length (in),Width (in),Height (in),Cylinders,Engine Displacement (L),Transmission Type,Transmission Speeds
1,1,1,Jack McCartney,Mazda Miata MX-5,1992.0,23.0,2121.00,53.0,155.51,66.14,48.03,4.0,1.6,0.0,5.0
2,1,1,Jack McCartney,Chyrsler New Yorker,1992.0,19.0,3337.00,63.0,193.70,68.90,53.54,6.0,3.3,1.0,4.0
3,1,1,Jack McCartney,Ford Crown Victoria,1992.0,20.0,3738.00,56.0,212.60,77.95,56.69,8.0,4.6,1.0,4.0
4,1,1,Jack McCartney,Cadillac Seville,1992.0,18.0,3557.00,63.0,204.33,74.41,53.94,8.0,4.9,1.0,4.0
5,1,1,Jack McCartney,Lexus LS400,1990.0,18.0,3760.00,54.0,196.85,71.65,55.12,8.0,4.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,25,5,Alex Bloom,Ford Mustang,2010.0,19.0,3750.00,53.0,188.19,74.02,55.91,8.0,4.6,1.0,5.0
622,25,5,Alex Bloom,Audi Q5 5DR SUV 2.0,2012.0,22.0,4089.57,53.0,182.28,74.80,65.35,4.0,2.0,1.0,8.0
623,25,5,Alex Bloom,Maserati Quattroporte,2012.0,15.0,4376.50,47.0,198.20,74.41,56.69,8.0,4.7,1.0,6.0
624,25,5,Alex Bloom,Mercedez-Benz CLS 550,2009.0,23.0,3982.00,52.0,193.70,73.62,54.72,8.0,5.5,1.0,6.0
625,25,5,Alex Bloom,Toyota FJ Cruiser,2009.0,26.0,4286.00,53.0,177.17,75.20,72.05,4.0,2.0,1.0,5.0

# Multiple Regression (all Parameters)

In [4]:
model = sm.OLS(
    df["MPG"],
    df[
        [
            "Model Year",
            "Weight (lbs)",
            "Weight Distribution (%)",
            "Length (in)",
            "Width (in)",
            "Height (in)",
            "Cylinders",
            "Engine Displacement (L)",
            "Transmission Type",
            "Transmission Speeds",
        ]
    ],
)
res = model.fit()
print(res.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:                    MPG   R-squared (uncentered):                   0.972
Model:                            OLS   Adj. R-squared (uncentered):              0.971
Method:                 Least Squares   F-statistic:                              1671.
Date:                Tue, 12 Aug 2025   Prob (F-statistic):                        0.00
Time:                        23:52:46   Log-Likelihood:                         -1418.3
No. Observations:                 494   AIC:                                      2857.
Df Residuals:                     484   BIC:                                      2899.
Df Model:                          10
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Model Year                  0.0121      0.004      3.376      0.001       0.005       0.019
Weight (lbs)               -0.0051      0.001     -6.493      0.000      -0.007      -0.004
Weight Distribution (%)     0.1544      0.043      3.574      0.000       0.070       0.239
Length (in)                -0.0080      0.021     -0.373      0.709      -0.050       0.034
Width (in)                 -0.0465      0.099     -0.469      0.639      -0.241       0.148
Height (in)                 0.1730      0.046      3.767      0.000       0.083       0.263
Cylinders                  -0.0845      0.278     -0.304      0.762      -0.631       0.462
Engine Displacement (L)    -1.9214      0.463     -4.146      0.000      -2.832      -1.011
Transmission Type           1.2734      0.435      2.927      0.004       0.419       2.128
Transmission Speeds         1.1586      0.281      4.127      0.000       0.607       1.710
==============================================================================
Omnibus:                      142.050   Durbin-Watson:                   1.510
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              481.886
Skew:                           1.307   Prob(JB):                    2.29e-105
Kurtosis:                       7.072   Cond. No.                     9.63e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 9.63e+03. This might indicate that there are
strong multicollinearity or other numerical problems.